services:
  - type: web
    name: lab-sheet-generator
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        sync: false
      - key: ONEDRIVE_CLIENT_ID
        sync: false
      - key: ONEDRIVE_CLIENT_SECRET
        sync: false
      - key: ONEDRIVE_REFRESH_TOKEN
        sync: false

databases:
  - name: labsheets-db
    databaseName: labsheets
    user: labsheets
    plan: free
